name: SFML_CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build_linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 5

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y libsfml-dev
        
    - name: Build
      run: |
        mkdir build/ && cd build/
        cmake -DCMAKE_BUILD_TYPE=Release ..
        make -j4

  build_macos:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 5

    - name: Install dependencies
      run: |
        brew install sfml
        
    - name: Build
      run: |
        mkdir build/ && cd build/
        cmake -DCMAKE_BUILD_TYPE=Release ..
        make -j4
